version: '3'

services:
  web:


    build: .

#    command: python manage.py runserver 0.0.0.0:8000
#    ports: 
#      - "8000:8000"
    ports:
          - "5000:5000"
    volumes:
          - .:/app
    tty: true

    command: tail -f /dev/null