#version: '3'
#
#services:
#  web:
#
#
#    build: .
#
##    command: python manage.py runserver 0.0.0.0:8000
##    ports:
##      - "8000:8000"
#    ports:
#          - "5000:5000"
#    volumes:
#          - .:/app
#    tty: true
#
#    command: tail -f /dev/null
version: '3.7'

services:
  pysonet_back:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  pysonet-db:
    image: postgres:12
    volumes:
      - pysonet_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432

volumes:
  pysonet_postgres_data:
